# Generated by Django 4.1.2 on 2022-11-02 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=35)),
                ('subject', models.CharField(choices=[('eng', 'English'), ('hin', 'Hindi'), ('sci', 'Science'), ('maths', 'Maths'), ('ai', 'A.i.'), ('other', 'Other')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
