# Generated by Django 4.1.2 on 2022-11-02 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clas_code_profile_clas_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='TCKWa', max_length=5),
        ),
        migrations.AlterField(
            model_name='clas',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
    ]
