# Generated by Django 4.1.2 on 2022-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clas_code_alter_clas_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='HG2WS', max_length=5),
        ),
    ]
