# Generated by Django 4.1.2 on 2022-11-02 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_clas_code_alter_clas_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='LyY8E', max_length=5),
        ),
        migrations.RemoveField(
            model_name='clas',
            name='students',
        ),
        migrations.AddField(
            model_name='clas',
            name='students',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
