# Generated by Django 4.1.2 on 2022-11-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_clas_code_remove_clas_students_clas_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='DhEpX', max_length=5),
        ),
    ]
