# Generated by Django 4.1.2 on 2022-11-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_clas_name_alter_clas_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.clas'),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='3yGd4', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='average',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
