# Generated by Django 4.1.2 on 2022-11-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profile_clas_alter_clas_code_alter_profile_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='QPXMn', max_length=5),
        ),
    ]
