# Generated by Django 4.1.2 on 2022-11-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_clas_code_remove_ebook_clas_ebook_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='MHXYA', max_length=5),
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='clas',
        ),
        migrations.AddField(
            model_name='ebook',
            name='clas',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.clas'),
            preserve_default=False,
        ),
    ]
