# Generated by Django 4.1.2 on 2022-11-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reading_reading_day_ebook_time_ebook_words_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reading',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='average',
        ),
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='VXwzf', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genres',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
