# Generated by Django 4.1.2 on 2022-11-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_clas_goal_alter_clas_code_alter_readbook_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='WwJDY', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=19),
        ),
    ]
