# Generated by Django 4.1.2 on 2022-11-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_clas_code_alter_profile_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='9uWH4', max_length=5),
        ),
    ]
