# Generated by Django 4.1.2 on 2022-11-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_readbook_finished_alter_clas_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='ZR4cB', max_length=5),
        ),
    ]
