# Generated by Django 4.1.2 on 2022-11-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_readbook_score_alter_clas_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='5WfJF', max_length=5),
        ),
    ]
