# Generated by Django 4.1.2 on 2022-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_clas_code_alter_ebook_avg_alter_ebook_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas',
            name='avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='UigtL', max_length=5),
        ),
    ]
