# Generated by Django 4.1.2 on 2023-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_clas_avg_alter_clas_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas',
            name='code',
            field=models.CharField(default='BRAUU', max_length=5),
        ),
        migrations.AlterField(
            model_name='clas',
            name='goal',
            field=models.IntegerField(default=10000),
        ),
    ]
